# Generated by Django 5.1.7 on 2025-03-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinguser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinguser',
            old_name='no_slots',
            new_name='total_slots',
        ),
    ]
