# Generated by Django 5.1.7 on 2025-04-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinguser', '0003_alter_user_email'),
        ('reservation', '0005_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinguser',
            name='parking_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
