# Generated by Django 5.1.7 on 2025-04-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinguser', '0005_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text="User's phone number", max_length=15, null=True, unique=True),
        ),
    ]
