# Generated by Django 5.1.7 on 2025-04-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinguser', '0006_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinguser',
            old_name='price',
            new_name='hourlyRate',
        ),
    ]
