# Generated by Django 5.1.7 on 2025-04-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinguser', '0007_rename_price_parkinguser_hourlyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinguser',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='dailyRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='levels',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='monthlyRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='openingHours',
            field=models.CharField(default='', max_length=10),
        ),
    ]
