# Generated by Django 5.1.7 on 2025-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinguser', '0008_parkinguser_address_parkinguser_dailyrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinguser',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
