# Generated by Django 5.1.7 on 2025-03-22 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkinguser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pid', models.IntegerField()),
                ('req_time', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_area', to='parkinguser.parkinguser')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField()),
                ('available', models.BooleanField()),
                ('reserved', models.TimeField()),
                ('parking_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lot', to='reservation.parkingarea')),
            ],
        ),
    ]
