# Generated by Django 5.1.7 on 2025-03-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslots',
            name='reserved_for',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parkingslots',
            name='reserved',
            field=models.BooleanField(),
        ),
    ]
