# Generated by Django 5.1.7 on 2025-03-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_parkingslots_reserved_for_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingslots',
            old_name='reserved_for',
            new_name='reserved_for_end',
        ),
        migrations.RemoveField(
            model_name='parkingarea',
            name='req_time',
        ),
        migrations.AddField(
            model_name='parkingarea',
            name='req_time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='parkingarea',
            name='req_time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='parkingslots',
            name='reserved_for_start',
            field=models.TimeField(null=True),
        ),
    ]
