# Generated by Django 5.1.7 on 2025-04-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qrcode',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('entry', 'entry'), ('exit', 'exit')], default='booked', max_length=50),
        ),
    ]
