# Generated by Django 5.1.7 on 2025-04-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_booking_qrcode_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='qrcode',
            new_name='qr_code',
        ),
    ]
