# Generated by Django 5.1.7 on 2025-04-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_rename_qrcode_booking_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qr/'),
        ),
    ]
